import type { ExploratoryRow, ExploratoryWeekCounts } from "./types";

export type ExpColumn = {
  key: string;
  label: string;
  num: keyof ExploratoryWeekCounts;
  den: keyof ExploratoryWeekCounts;
  tooltip: string;
  profileNote: string;
  fmt?: "pct1" | "plain2" | "plain3" | "signed3";
  lowerBetter?: boolean;
  noHeatmap?: boolean;
};

type ExpSection = { title: string; columns: ExpColumn[] };

export const SERIES_OFFENSE: ExpColumn[] = [
  {
    key: "seriesConversionRate",
    label: "Series Conversion %",
    num: "seriesConversions",
    den: "seriesOpportunities",
    tooltip: "How often a fresh set of downs ends with another first down or a touchdown. It counts conversions on any down, not just 3rd down.",
    profileNote: "Keeps the chains moving on any down",
  },
  {
    key: "recoveryRate",
    label: "Recovery %",
    num: "recoveredSeries",
    den: "recoveryOpportunities",
    tooltip: "After an unsuccessful 1st- or 2nd-down play, how often the offense still earns another first down or touchdown in that same series.",
    profileNote: "Bounces back after a bad early down",
  },
  {
    key: "longDownAvoidanceRate",
    label: "Avoid 3rd & Long %",
    num: "longDownAvoidanceSeries",
    den: "eligibleSeries",
    tooltip: "How often the offense gets through a series without facing 3rd-and-7 or longer. Higher means it stays on schedule more often.",
    profileNote: "Stays out of obvious passing situations",
  },
];

const SERIES_DEFENSE: ExpColumn[] = [
  {
    key: "seriesStopRate",
    label: "Series Stop %",
    num: "seriesStops",
    den: "seriesStopOpportunities",
    tooltip: "How often the defense ends an opponent's fresh set of downs before the offense gains another first down or scores a touchdown.",
    profileNote: "Ends an opponent's fresh set of downs",
  },
  {
    key: "closeoutRate",
    label: "Closeout %",
    num: "closeouts",
    den: "closeoutOpportunities",
    tooltip: "After the defense wins an early down, how often it finishes the series without allowing another first down or touchdown.",
    profileNote: "Finishes the job after winning an early down",
  },
  {
    key: "longDownCreationRate",
    label: "Force 3rd & Long %",
    num: "longDownsCreated",
    den: "longDownCreationOpportunities",
    tooltip: "How often the defense forces an opponent into 3rd-and-7 or longer. Higher means more obvious passing situations created.",
    profileNote: "Creates obvious passing situations",
  },
];

const POSSESSIONS_OFFENSE: ExpColumn[] = [
  {
    key: "cleanDriveRate", label: "Clean Drive %",
    num: "cleanDrives", den: "eligibleDrives",
    tooltip: "How often the offense gets through an entire possession without a turnover, sack, TFL, costly accepted penalty, or failed 4th down.",
    profileNote: "Avoids the self-inflicted mistakes that stall a drive",
  },
  {
    key: "driveKillerRate", label: "Drive Killer %",
    num: "drivesKilled", den: "drivesWithKillerEvent",
    tooltip: "How often a major mistake (turnover, sack, TFL, costly penalty, failed 4th down) actually puts the drive away for good, of the drives that had one.",
    profileNote: "How often one mistake ends the whole possession",
    lowerBetter: true,
  },
];

const POSSESSIONS_DEFENSE: ExpColumn[] = [
  {
    key: "cleanDriveRateAllowed", label: "Clean Drive Allowed %",
    num: "cleanDrivesAllowed", den: "eligibleDrivesFaced",
    tooltip: "How often the opponent's offense gets through an entire possession against this defense without a mistake. Lower is better defense.",
    profileNote: "Lets opponents drive mistake-free too often, or not",
    lowerBetter: true,
  },
  {
    key: "driveKillerRateForced", label: "Drive Killer Forced %",
    num: "drivesKilledForced", den: "drivesWithKillerEventForced",
    tooltip: "Of opponent drives that had a major mistake against this defense, how often the defense actually finished the drive off.",
    profileNote: "Turns an opponent's mistake into a dead drive",
  },
];

const STYLE_RISK: ExpColumn[] = [
  {
    key: "explosiveDependency", label: "Explosive Dependency %",
    num: "explosivePositiveEpa", den: "positiveEpa",
    tooltip: "Share of an offense's positive EPA generated by explosive plays (rush 10+ yards, pass 20+ yards). Descriptive, not a quality signal -- high dependency can mean dangerous, or volatile.",
    profileNote: "How much of the offense rides on its biggest plays",
    noHeatmap: true,
  },
  {
    key: "nonExplosiveEpaPerPlay", label: "Non-Explosive EPA/play",
    num: "nonExplosiveEpa", den: "nonExplosivePlays",
    tooltip: "How efficient the offense is when explosive plays are removed from the picture.",
    profileNote: "How the offense performs once the big plays are set aside",
    fmt: "signed3",
  },
  {
    key: "failureRate", label: "Failure Rate",
    num: "negativeEpaPlays", den: "epaEligiblePlays",
    tooltip: "How often the offense produces a negative-EPA play.",
    profileNote: "How often a play actively hurts the offense",
    lowerBetter: true,
  },
  {
    key: "averageFailureDamage", label: "Avg Failure Damage",
    num: "negativeEpaMagnitudeSum", den: "negativeEpaPlays",
    tooltip: "How costly the offense's bad plays are when they happen.",
    profileNote: "How bad the bad plays really are",
    fmt: "plain3", lowerBetter: true,
  },
  {
    key: "failureBurden", label: "Failure Burden",
    num: "negativeEpaMagnitudeSum", den: "epaEligiblePlays",
    tooltip: "How much negative EPA the offense gives away per play through mistakes and failed plays. Failure Rate times Average Failure Damage.",
    profileNote: "The full cost of an offense's mistakes, per play",
    fmt: "plain3", lowerBetter: true,
  },
  {
    key: "failurePressure", label: "Failure Pressure",
    num: "opponentNegativeEpaMagnitudeSum", den: "opponentEpaEligiblePlays",
    tooltip: "How much negative EPA the defense forces opponents to absorb per play.",
    profileNote: "How much damage the defense inflicts through opponent mistakes",
    fmt: "plain3",
  },
];

// Points per Scoring Opportunity (and its opponent mirror) is deliberately
// NOT a column here -- a row-level check found it byte-for-byte identical to
// the existing Finishing Drives points-per-opportunity stat (0 mismatches
// across 1,616 2025 rows). Exposing it under a second name on this page
// would just be the same number twice; see Finishing Drives on /advanced
// instead. The underlying scoringOpportunity* fields still get computed and
// exported (useful for other research), just never surfaced as a page column.

export const SECTIONS: ExpSection[] = [
  { title: "Series · Offense", columns: SERIES_OFFENSE },
  { title: "Series · Defense", columns: SERIES_DEFENSE },
  { title: "Possessions · Offense", columns: POSSESSIONS_OFFENSE },
  { title: "Possessions · Defense", columns: POSSESSIONS_DEFENSE },
  { title: "Style / Risk", columns: STYLE_RISK },
];

export const ALL_COLUMNS: ExpColumn[] = SECTIONS.flatMap((s) => s.columns);
export const SECTION_START_KEYS = new Set(SECTIONS.map((s) => s.columns[0]?.key).filter(Boolean));

export type Aggregated = {
  team: string;
  slug: string;
  teamId: number;
  conf: string;
  wk: Partial<ExploratoryWeekCounts>;
  [key: string]: unknown;
};

type FanTier = { label: string; className: string };

export function fanTier(rank: number | null, total: number, smallSample: boolean, neutral = false): FanTier {
  if (smallSample) return { label: "Small Sample", className: "profile-tier--sample" };
  if (!rank || total <= 0) return { label: "No Rank", className: "profile-tier--sample" };
  const percentile = rank / total;
  if (neutral) return { label: percentile <= .33 ? "High Dependency" : percentile > .67 ? "Low Dependency" : "Balanced", className: "profile-tier--sample" };
  if (percentile <= 0.10) return { label: "Elite", className: "profile-tier--elite" };
  if (percentile <= 0.25) return { label: "Strong", className: "profile-tier--strong" };
  if (percentile <= 0.40) return { label: "Good", className: "profile-tier--good" };
  if (percentile <= 0.60) return { label: "Average", className: "profile-tier--average" };
  if (percentile <= 0.80) return { label: "Below Avg", className: "profile-tier--below" };
  return { label: "Needs Work", className: "profile-tier--poor" };
}


/** Research denominator floors. Secondary existing diagnostic columns retain 20. */
export function minimumN(col: ExpColumn): number {
  if (["seriesOpportunities", "seriesStopOpportunities", "eligibleSeries", "longDownCreationOpportunities"].includes(col.den)) return 25;
  if (["recoveryOpportunities", "closeoutOpportunities"].includes(col.den)) return 16;
  if (["failureRate", "averageFailureDamage"].includes(col.key)) return 20;
  return 10;
}

export function aggregateExploratory(byWeek: Record<string, ExploratoryRow[]>, weeks: number[], start: number, end: number): Aggregated[] {
  const byTeam = new Map<string, Aggregated>();
  for (const week of weeks.filter(w => w >= start && w <= end)) {
    for (const row of byWeek[String(week)] || []) {
      let acc = byTeam.get(row.slug);
      if (!acc) {
        acc = { team: row.team, slug: row.slug, teamId: row.teamId, conf: row.conf, wk: {} };
        byTeam.set(row.slug, acc);
      }
      for (const field of Object.keys(row.wk) as (keyof ExploratoryWeekCounts)[]) {
        const value = row.wk[field];
        if (typeof value === "number" && Number.isFinite(value)) acc.wk[field] = (acc.wk[field] ?? 0) + value;
      }
    }
  }
  return [...byTeam.values()].map(acc => {
    const out: Aggregated = { ...acc };
    for (const col of ALL_COLUMNS) {
      const n = acc.wk[col.den] ?? 0;
      out[col.key] = n > 0 ? (acc.wk[col.num] ?? 0) / n : null;
      out[`${col.key}_n`] = n;
    }
    return out;
  });
}

export function rankExploratory(teams: Aggregated[]): Aggregated[] {
  const out = teams.map(t => ({ ...t }));
  for (const col of ALL_COLUMNS) {
    const eligible = out.filter(t => typeof t[col.key] === "number" && Number.isFinite(t[col.key]) && Number(t[`${col.key}_n`]) >= minimumN(col));
    for (const team of out) {
      team[`_rank_${col.key}`] = eligible.includes(team) ? 1 + eligible.filter(t => col.lowerBetter ? Number(t[col.key]) < Number(team[col.key]) : Number(t[col.key]) > Number(team[col.key])).length : null;
    }
  }
  return out;
}
