"""Deterministic display-only export of the validated additive matchup models.

Never called by rating or prediction pipelines. Historical calibration uses only
out-of-sample opponent effects from seasons earlier than the displayed season.
Model coefficients reset each season and are fitted on strictly earlier weeks.
Tier 1 retains its research site-week clock/population; Wave 2 retains its more
conservative canonical-week clock and FBS-vs-FBS population.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
from collections import defaultdict
from pathlib import Path
from statistics import mean, pstdev

from cfb_analytics.analytics.exploratory_predictive_value import _fit_ols
from cfb_analytics.analytics.exploratory_matchup_value import PAIRINGS as TIER, build_site_week_map
from cfb_analytics.analytics.exploratory_wave2_predictive_value import load_exploratory_counts
from cfb_analytics.analytics.ppa_core_rating_backtest import load_canonical_team_games
from cfb_analytics.derived.pregame import _pk

ROOT = Path(__file__).resolve().parents[3]
VERSION = "exploratory-matchup-additive-v1"
CALIBRATION = ROOT / "data/models/exploratory-matchups/calibration.json"
OUTPUT = ROOT / "data/processed/private/exploratory-matchups"
SEASONS = (2014, 2015, 2016, 2017, 2018, 2019, 2021, 2022, 2023, 2024, 2025, 2026)
DISPLAY_QUANTILE = .70


def spec(key, title, off, defense, off_label, def_label, lower=False, style=False):
    return dict(key=key, title=title, off_num=off[0], off_den=off[1], def_num=defense[0],
                def_den=defense[1], off_min_cum_den=10, def_min_cum_den=10,
                target_min_den=1e-12, min_train=40, off_label=off_label,
                def_label=def_label, lower=lower, style=style, tier="wave2")


PAIRS = {
    "series_conversion": {**TIER["series_conversion"], "key": "series_conversion", "title": "Sustaining drives", "off_label": "Series Conversion", "def_label": "Series Stop", "lower": False, "style": False, "tier": "tier1", "target_min_den": 5, "min_train": 20},
    "recovery_closeout": {**TIER["recovery_closeout"], "key": "recovery_closeout", "title": "Recovering from bad downs", "off_label": "Recovery", "def_label": "Closeout", "lower": False, "style": False, "tier": "tier1", "target_min_den": 5, "min_train": 20},
    "long_down": {**TIER["long_down"], "key": "long_down", "title": "Staying on schedule", "off_label": "Avoid 3rd & Long", "def_label": "Force 3rd & Long", "lower": True, "style": False, "tier": "tier1", "target_min_den": 5, "min_train": 20},
    "clean_drive": spec("clean_drive", "Playing clean", ("cleanDrives", "eligibleDrives"), ("cleanDrivesAllowed", "eligibleDrivesFaced"), "Clean Drive", "Clean Drive Allowed"),
    "drive_killer": spec("drive_killer", "Surviving mistakes", ("drivesKilled", "drivesWithKillerEvent"), ("drivesKilledForced", "drivesWithKillerEventForced"), "Drive Killer", "Drive Killer Forced", lower=True),
    "failure": spec("failure", "Limiting negative plays", ("negativeEpaMagnitudeSum", "epaEligiblePlays"), ("opponentNegativeEpaMagnitudeSum", "opponentEpaEligiblePlays"), "Failure Burden", "Failure Pressure", lower=True),
    "explosive": spec("explosive", "Big-play profile", ("explosivePositiveEpa", "positiveEpa"), ("explosivePlaysAllowed", "explosiveEligiblePlaysAllowed"), "Explosive Dependency", "Explosive Rate Allowed", style=True),
}
DEFINITIONS = {
    "series_conversion": "Share of eligible series converted into another first down or touchdown; paired with the defense's series stop rate.",
    "recovery_closeout": "Share of recovery opportunities converted after an early-down failure; paired with the defense's closeout rate.",
    "long_down": "Long-down exposure is longDownSeries / eligibleSeries. The offense's displayed Avoid 3rd & Long value is its complement. Projection and effect refer to facing 3rd-and-long.",
    "clean_drive": "Share of validated possessions without a turnover, sack, TFL, costly accepted offensive penalty, or failed fourth down. Self-recovered fumbles do not disqualify a drive.",
    "drive_killer": "Among mistake-containing drives, the share without another first down or touchdown after the final qualifying mistake. The denominator is mistake-containing drives, not all drives.",
    "failure": "Negative EPA magnitude per EPA-eligible play. The defensive counterpart measures the damage opponents absorb.",
    "explosive": "Share of positive EPA generated by explosive plays (rush 10+ yards, pass 20+ yards), paired with the defense's explosive-play frequency allowed. Dependency is style, not quality.",
}


def quantile(values, q):
    if not values:
        return None
    vs = sorted(values); pos = (len(vs)-1)*q; lo = int(pos); hi = min(lo+1, len(vs)-1)
    return vs[lo] + (vs[hi]-vs[lo])*(pos-lo)


def calibration(values):
    return dict(n=len(values), quantiles=[quantile(values, i/100) for i in range(101)])


def fit_model(rows, features):
    weights, centers, scales = _fit_ols(rows, tuple(features), "target")
    if weights is None:
        return None
    coefficients = [weights[i+1]/scales[i] for i in range(len(features))]
    return dict(intercept=weights[0]-sum(c*m for c,m in zip(coefficients,centers)),
                coefficients=dict(zip(features,coefficients)), n=len(rows), ridge=1e-6,
                trainingSha=hashlib.sha256(json.dumps(rows,sort_keys=True,separators=(",", ":")).encode()).hexdigest())


def project(model, off, defense):
    return model["intercept"] + model["coefficients"].get("off",0)*off + model["coefficients"].get("defense",0)*defense


def ranks(values, lower):
    # Competition ranks: equal raw rates receive equal national ranks.
    return {team:1+sum(v<value if lower else v>value for v in values.values()) for team,value in values.items()}


def summarize_edge(pair, offense, defense, off_rate, def_rate, off_n, def_n, off_rank, def_rank, models, distribution):
    if off_n<pair["off_min_cum_den"] or def_n<pair["def_min_cum_den"] or off_rate is None or def_rate is None or not models:
        return None
    expected=project(models["additive"],off_rate,def_rate)
    usual=project(models["offenseOnly"],off_rate,def_rate)
    # Do not clip an extrapolation into an apparently valid percentage.
    if not all(math.isfinite(v) and v>=0 and (pair["key"]=="failure" or v<=1) for v in (expected,usual)):
        return None
    effect=expected-usual
    qs=distribution["quantiles"]
    threshold=qs[70] if distribution["n"]>=pair["min_train"] else None
    percentile=sum(q is not None and abs(effect)>=q for q in qs)/len(qs) if threshold is not None else None
    advantage=None if pair["style"] or effect==0 else (offense if (effect<0)==pair["lower"] else defense)
    return dict(pairing=pair["key"],title=pair["title"],offenseTeam=offense,defenseTeam=defense,
                offenseLabel=pair["off_label"],defenseLabel=pair["def_label"],
                offenseRate=1-off_rate if pair["key"]=="long_down" else off_rate,
                defenseRate=def_rate, offenseRank=off_rank,defenseRank=def_rank,
                offenseN=off_n,defenseN=def_n,offenseMinN=pair["off_min_cum_den"],defenseMinN=pair["def_min_cum_den"],
                expected=expected,offenseOnly=usual,opponentEffect=effect,advantageTeam=advantage,
                style=pair["style"],unit="epa" if pair["key"]=="failure" else "rate",
                threshold=threshold,effectPercentile=percentile,
                meaningful=threshold is not None and abs(effect)>=threshold and abs(effect)>0,
                definition=DEFINITIONS[pair["key"]],modelId=models["id"])


def select_edges(edges, limit=5):
    ordered=sorted((e for e in edges if e["meaningful"]),key=lambda e:(-e["effectPercentile"],e["offenseTeam"],e["pairing"]))
    # Represent both attacking directions when both have meaningful evidence.
    selected=[]
    for team in sorted({e["offenseTeam"] for e in ordered}):
        selected.append(next(e for e in ordered if e["offenseTeam"]==team))
    for edge in ordered:
        if len(selected)>=limit: break
        if edge not in selected: selected.append(edge)
    return sorted(selected,key=lambda e:(-e["effectPercentile"],e["offenseTeam"],e["pairing"]))[:limit]


def build_pair(pair, season, records, targets, identity, prior_calibration):
    def clock(r): return (r["siteWeek"],) if pair["tier"]=="tier1" else tuple(r["pk"])
    parts=defaultdict(list); games=defaultdict(list)
    for r in records: parts[clock(r)].append(r)
    for g in targets: games[clock(g)].append(g)
    sums=defaultdict(lambda:defaultdict(float)); train=[]; effects=[]; result={}; artifacts={}
    history_site_weeks=[]
    for week in sorted(set(parts)|set(games)):
        rates={}
        for team in sums:
            s=sums[team]; od=s[pair["off_den"]]; dd=s[pair["def_den"]]
            rates[team]=(s[pair["off_num"]]/od if od>=pair["off_min_cum_den"] else None,
                         s[pair["def_num"]]/dd if dd>=pair["def_min_cum_den"] else None,od,dd)
        off_ranks=ranks({t:r[0] for t,r in rates.items() if t in identity and r[0] is not None},pair["lower"] and pair["key"]!="explosive")
        def_ranks=ranks({t:r[1] for t,r in rates.items() if t in identity and r[1] is not None},pair["key"] in ("clean_drive","explosive"))
        models=None
        dist=prior_calibration if prior_calibration and prior_calibration["n"]>=pair["min_train"] else calibration(effects)
        if len(train)>=pair["min_train"]:
            additive=fit_model(train,["off","defense"]); offense_only=fit_model(train,["off"])
            if additive and offense_only:
                model_id=f"{VERSION}/{season}/{'-'.join(map(str,week))}/{pair['key']}"
                models=dict(id=model_id,additive=additive,offenseOnly=offense_only,
                            trainBefore=list(week),clock="siteWeek" if pair["tier"]=="tier1" else "canonicalWeek",
                            throughSiteWeek=max(history_site_weeks,default=-1),targetStd=pstdev(r["target"] for r in train),
                            threshold=dist["quantiles"][70],thresholdN=dist["n"])
                artifacts[model_id]=models
        # All targets in this fold use the same pregame snapshot and fitted models.
        for game in games.get(week,[]):
            edges=[]
            # Guard against any calendar inconsistency; never use a later site week.
            if history_site_weeks and max(history_site_weeks)>=game["siteWeek"]:
                result[game["gameId"]]=[]; continue
            for offense,defense in ((game["homeTeam"],game["awayTeam"]),(game["awayTeam"],game["homeTeam"])):
                off=rates.get(offense,(None,None,0,0)); de=rates.get(defense,(None,None,0,0))
                edge=summarize_edge(pair,offense,defense,off[0],de[1],off[2],de[3],off_ranks.get(offense),def_ranks.get(defense),models,dist)
                if edge:
                    edge["throughWeek"]=max(history_site_weeks,default=-1)
                    edges.append(edge)
            result[game["gameId"]]=edges
        # Hold-out effects used for later calibration need completed, eligible targets.
        pending=[]
        for row in parts.get(week,[]):
            off=rates.get(row["team"],(None,None,0,0)); de=rates.get(row.get("opponent"),(None,None,0,0))
            den=row.get(pair["off_den"],0) or 0; num=row.get(pair["off_num"])
            if off[0] is not None and de[1] is not None and den>=pair["target_min_den"] and num is not None:
                obs=dict(off=off[0],defense=de[1],target=num/den)
                pending.append(obs)
                if models:
                    expected=project(models["additive"],off[0],de[1]); usual=project(models["offenseOnly"],off[0],de[1])
                    if all(math.isfinite(x) and x>=0 and (pair["key"]=="failure" or x<=1) for x in (expected,usual)):
                        effects.append(abs(expected-usual))
        train.extend(pending)
        for row in parts.get(week,[]):
            for field in {pair["off_num"],pair["off_den"],pair["def_num"],pair["def_den"]}:
                value=row.get(field)
                if isinstance(value,(int,float)) and math.isfinite(value): sums[row["team"]][field]+=value
            history_site_weeks.append(row["siteWeek"])
    return result,artifacts,effects


def load_inputs(season):
    mapping,_,_=build_site_week_map(season)
    expl=load_exploratory_counts(season)
    canonical=load_canonical_team_games(season)
    raw_games={str(g["id"]):g for p in sorted((ROOT/f"data/raw/cfbd/season={season}").glob("season_type=*/week=*/games.json")) for g in json.loads(p.read_text())}
    identity={r["team"] for r in json.loads((ROOT/f"data/canonical/season={season}/teams.json").read_text()) if r.get("classification")=="fbs"}
    def prepared(r):
        gid=str(r["gameId"])
        return {**r,"gameId":gid,"siteWeek":mapping[gid],"pk":list(_pk(r))}
    tier=[prepared(r) for (gid,_),r in expl.items() if gid in mapping]
    wave=[prepared({**r,**expl.get((str(r["gameId"]),r["team"]),{})}) for r in canonical if str(r["gameId"]) in mapping]
    schedule=json.loads((ROOT/f"web/public/data/schedule/{season}.json").read_text())
    targets=[]
    for gs in schedule["byWeek"].values():
        for g in gs:
            raw=raw_games.get(g["gameId"])
            if raw and g["gameId"] in mapping:
                targets.append({**g,"siteWeek":mapping[g["gameId"]],"pk":list(_pk(raw))})
    return tier,wave,targets,identity


def build_season(season, calibrations):
    tier,wave,targets,identity=load_inputs(season)
    all_edges=defaultdict(list); artifacts={}; effects={}
    for key,pair in PAIRS.items():
        result,models,es=build_pair(pair,season,tier if pair["tier"]=="tier1" else wave,targets,identity,calibrations.get(key))
        for gid,edges in result.items(): all_edges[gid].extend(edges)
        artifacts.update(models); effects[key]=es
    by_game={}
    for game in targets:
        es=all_edges[game["gameId"]]; selected=select_edges(es)
        by_game[game["gameId"]]=dict(season=season,gameId=game["gameId"],week=game["siteWeek"],
            status="ready" if selected else "even" if any(e["threshold"] is not None for e in es) else "limited",
            availablePairings=len(es),possiblePairings=14,edges=selected)
    return dict(version=VERSION,byGame=by_game,models=artifacts),effects


def atomic_json(path,payload):
    path.parent.mkdir(parents=True,exist_ok=True)
    temporary=path.with_suffix(".tmp")
    temporary.write_text(json.dumps(payload,sort_keys=True,separators=(",",":"),allow_nan=False)+"\n")
    temporary.replace(path)


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--season",type=int)
    parser.add_argument("--calibrate",action="store_true",help="Rebuild historical OOS magnitude distributions and all season exports")
    args=parser.parse_args()
    if args.calibrate:
        history=defaultdict(list); by_season={}; audit={}
        for season in SEASONS:
            cs={k:calibration(history[k]) for k in PAIRS}
            by_season[str(season)]=cs
            payload,effects=build_season(season,cs)
            atomic_json(OUTPUT/f"{season}.json",payload)
            audit[str(season)]={"games":len(payload["byGame"]),"shown":sum(len(g["edges"]) for g in payload["byGame"].values()),"effectSamples":{k:len(v) for k,v in effects.items()}}
            if season<=2025:
                for k,es in effects.items(): history[k].extend(es)
            print(f"Matchup export {season}: {audit[str(season)]['games']} games",flush=True)
        atomic_json(CALIBRATION,dict(version=VERSION,quantile=DISPLAY_QUANTILE,bySeason=by_season,audit=audit))
    else:
        season=args.season or 2026
        c=json.loads(CALIBRATION.read_text())
        if c["version"]!=VERSION or str(season) not in c["bySeason"]:
            raise ValueError("Rebuild calibration for this season with --calibrate")
        payload,_=build_season(season,c["bySeason"][str(season)])
        atomic_json(OUTPUT/f"{season}.json",payload)
        print(f"Matchup export {season}: {len(payload['byGame'])} games",flush=True)

if __name__=="__main__": main()
